language: generic
dist: trusty

before_install:
  - sudo apt-get install -y squashfs-tools

script:
  - chmod +x QtCreator
  - ./QtCreator
after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh polaroid-fy*-x86_64.AppImage*
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
